# Generated by Django 5.0.2 on 2024-04-22 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='stade_photos/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=20)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('num_tel', models.CharField(max_length=20)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('type_compte', models.CharField(choices=[('player', 'Player'), ('owner', 'Owner'), ('admin', 'Admin')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], max_length=20)),
                ('stade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footiefunApplication.stade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footiefunApplication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tournoit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('type_tournoit', models.CharField(choices=[('2v2', '2 VS 2'), ('3v3', '3 VS 3'), ('4v4', '4 VS 4')], max_length=20)),
                ('description', models.TextField()),
                ('stade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footiefunApplication.stade')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipeDomicile', models.IntegerField()),
                ('id_equipeExtérieur', models.IntegerField()),
                ('date_match', models.DateTimeField()),
                ('description', models.TextField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footiefunApplication.reservation')),
                ('tournoit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footiefunApplication.tournoit')),
            ],
        ),
    ]
