# Generated by Django 5.0.2 on 2024-04-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footiefunApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stade',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
